# Fly.io configuration
app = "fusion-starter"
primary_region = "iad"

[build]
  builder = "heroku"

[env]
  MONGODB_URI = "mongodb+srv://rawatt046_db_user:UoMiqyms1nx2S4ju@cluster0.rrladca.mongodb.net/optimizer?appName=Cluster0"
  JWT_SECRET = "niteshsingh"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
