[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  node_bundler = "esbuild"
  included_files = ["server/**"]
  # ⚠️ remove "external_node_modules" — not needed when using esbuild

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
